// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBccwJFt0WwaV51ekU8cHuGXaysPrvR9kc',
    appId: '1:131828782150:web:cf039469738b855e6da647',
    messagingSenderId: '131828782150',
    projectId: 'instgram-clone-fc718',
    authDomain: 'instgram-clone-fc718.firebaseapp.com',
    storageBucket: 'instgram-clone-fc718.appspot.com',
    measurementId: 'G-KHNQ135HJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGWHVrD3mwnnv_RW1hdr6G6l14xiG2ce0',
    appId: '1:131828782150:android:712f93b78a572fe56da647',
    messagingSenderId: '131828782150',
    projectId: 'instgram-clone-fc718',
    storageBucket: 'instgram-clone-fc718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqehE2S9LHfYoIel_yVhX8UuaqeIK47fQ',
    appId: '1:131828782150:ios:bdeaa403dbb644446da647',
    messagingSenderId: '131828782150',
    projectId: 'instgram-clone-fc718',
    storageBucket: 'instgram-clone-fc718.appspot.com',
    iosClientId: '131828782150-ifn8kch6bfsrsuht7nga4ceoouifocfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.instgram',
  );
}
